services:
    pad.menu.builder:
        class: Pad\MenuBundle\Menu\Builder
        arguments:
            - @knp_menu.factory
            - @ezpublish.api.service.search
            - @router
            - @ezpublish.config.resolver
            - @ezpublish.api.service.location
            - @ezpublish.translation_helper
    pad.menu.top:
        class: Pad\MenuBundle\Menu\Builder
        factory_service: pad.menu.builder
        factory_method: createTopMenu
        arguments: [ @request ]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: top } # The alias is what is used to retrieve the menu
